platform :ios, '13.0'

target 'Plugin' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods
  pod 'TwitterLoginKit'
  pod 'Capacitor'
end

target 'PluginTests' do
  use_frameworks!
  pod 'TwitterLoginKit'
  pod 'Capacitor'
end
