platform :ios, '13.0'

def capacitor_pods
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Capacitor', :path => '../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../node_modules/@capacitor/ios'

  pod 'GoogleSignIn', '~> 6.0.1'
  pod 'TwitterKit'
  pod 'FBSDKLoginKit', '14.1.0'
  pod 'FBSDKCoreKit', '14.1.0'
end

target 'PluginTests' do
  use_frameworks!

  pod 'GoogleSignIn', '~> 6.0.1'
  pod 'TwitterKit'
  pod 'FBSDKLoginKit', '14.1.0'
  pod 'FBSDKCoreKit', '14.1.0'
  pod 'Capacitor', :path => '../node_modules/@capacitor/ios'
end

post_install do |installer|
  assertDeploymentTarget(installer)
end